#!/bin/bash
#
# Autor= João Batista Ribeiro
# Bugs, Agradecimentos, Criticas "construtivas"
# Mande me um e-mail. Ficarei Grato!
# e-mail: joao42lbatista@gmail.com
#
# Este programa é um software livre; você pode redistribui-lo e/ou
# modifica-lo dentro dos termos da Licença Pública Geral GNU como
# publicada pela Fundação do Software Livre (FSF); na versão 2 da
# Licença, ou (na sua opinião) qualquer versão.
#
# Este programa é distribuído na esperança que possa ser útil,
# mas SEM NENHUMA GARANTIA; sem uma garantia implícita de ADEQUAÇÃO a
# qualquer MERCADO ou APLICAÇÃO EM PARTICULAR.
#
# Veja a Licença Pública Geral GNU para mais detalhes.
# Você deve ter recebido uma cópia da Licença Pública Geral GNU
# junto com este programa, se não, escreva para a Fundação do Software
#
# Livre(FSF) Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script: Clone some Slackware repository to a local source
#
# Last update: 03/11/2016
#
# Tip: Use the file insed one "old" ISO to make less things to download

mirrorSource="ftp://ftp.osuosl.org/.2/slackware/"

echo -e "\nDefault mirror: $mirrorSource"

echo -en "\nWant change de default mirror?\n(y)es - (n)o (enter to no): "
read changeMirror

if [ "$changeMirror" == 'y' ]; then
    mirrorSource=''

    while echo "$mirrorSource" | grep -v -q -E "ftp|http"; do
        echo -en "\nInsert the new mirror: "
        read mirrorSource
    done

    echo -e "\nNew mirror: $mirrorSource\n"
fi

echo -en "\nWith version Slackware you want? (enter to 14.2): "
read versioSlackware

if [ "$versioSlackware" == '' ]; then
    versioSlackware="14.2"
fi

echo -en "\nWith arch you want? \n(1) - 32 bits or (2) to 64 bits (enter to 64 bits): "
read choosedArch

if [ "$choosedArch" == '1' ]; then
    choosedArch=''
else
    choosedArch="64"
fi

versionDownload=slackware$choosedArch-$versioSlackware

echo -en "\nWant download the source code?\n(y)es - (n)o (enter to no): "
read downloadSource

echo -en "\nWill download (by lftp) \"$versionDownload\" "
if [ "$downloadSource" == 'y' ]; then
    echo -n "with"
else
    echo -n "without"
fi
echo -e " the source code from \"$mirrorSource\""

echo -en "\nWant continue?\n(y)es - (n)o (enter to yes): "
read contineLftp

if [ "$contineLftp" == 'n' ]; then
    echo -e "\nJust exiting by user choice\n"
else
    echo -e "\nDownloading files\nPlease wait...\n"

    if [ "$downloadSource" == 'y' ]; then
        lftp -c 'open '$mirrorSource'; mirror -c -e '$versionDownload'/'
        # -c continue a mirror job if possible
        # -e delete files not present at remote site
    else
        lftp -c 'open '$mirrorSource'; mirror -c -e --exclude source/ --exclude patches/source/ '$versionDownload'/'
    fi

    cd $versionDownload/

    echo -en "\nWant check the integrity of downloaded files?\n(y)es - (n)o (enter to no): "
    read checkFiles

    if [ "$checkFiles" == 'y' ]; then
        echo -e "\nChecking the integrity of the files\nPlease wait...\n"
        if [ "$downloadSource" == 'y' ]; then
            checkFilesResult=`tail +13 CHECKSUMS.md5 | md5sum -c --quiet`
        else
            checkFilesResult=`tail +13 CHECKSUMS.md5 | grep -v "source/" | grep -v "patches/source/" | md5sum -c --quiet`
        fi

        if [ "$checkFilesResult" == '' ]; then
            echo -e "\nFiles integrity: Good - files are equal to the server\n"
        else
            echo -e "\nFiles integrity: Bad - files different from the server\n"
            echo -e "$checkFilesResult"
        fi
    fi

    cd ..

    echo -en "\nWant create a ISO file from downloaded folder?\n(y)es - (n)o (enter to no): "
    read generateISO

    datePartName=`date +%Hh-%Mmin-%dday-%mmouth-%Yyear`
    isoFileName=$versionDownload\_date-$datePartName

    if [ "$generateISO" == 'y' ]; then
        olderIsoSlackware=`ls | grep "slackware.*iso"`

        if [ "$olderIsoSlackware" != '' ]; then
            echo -e "\nOlder ISO file slackware:\n$olderIsoSlackware"
            echo -en "\nDelete those older ISO files before continue?\n(y)es - (n)o (enter to no): "
            read deleteOlderIso

            if [ "$deleteOlderIso" == 'y' ]; then
                rm slackware*.iso
            fi
        fi

        echo -e "\nCreating ISO file\nPlease wait...\n"

        mkisofs -pad -r -J -quiet -o $isoFileName.iso $versionDownload/
        # -pad   Pad output to a multiple of 32k (default)
        # -r     Generate rationalized Rock Ridge directory information
        # -J     Generate Joliet directory information
        # -quiet Run quietly
        # -o     Set output file name

        echo -e "\nThe file \"$isoFileName.iso\" was generated by the folder $versionDownload/\n"
    else
        echo -e "\n\nExiting...\n\nIf you want create a ISO file use:\nmkisofs -pad -r -J -o $isoFileName.iso $versionDownload/\n"
    fi
fi
